theme: jekyll-theme-slate
title: Promacanthus‘s manual 
title_separator: Sample Page | My Awesome Site.
name: "Bowen Zhu"
description: "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url: "https://promacanthus.github.io/Notes/"